/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.1
 * Generated at: 2024-10-19 04:07:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import model.*;

public final class RegistrarProducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#c5dec9\">\r\n");
      out.write("    <h1 align=\"center\">Registrar Producto</h1>\r\n");
      out.write("    <form action=\"ControladorProducto\" method=\"post\">\r\n");
      out.write("        <table border=\"2\" align=\"center\">\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Nombre del Producto</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"nombresusti\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Precio de Compra</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"preciocompsusti\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Precio de Venta</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"precioventasusti\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Estado</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"estadosusti\" required>\r\n");
      out.write("                \r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>Descripción</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"descripsusti\" required></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\" align=\"center\">\r\n");
      out.write("                    <input type=\"submit\" value=\"Ingresar Producto\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("    <h2 align=\"center\">Listado de Productos</h2>\r\n");
      out.write("    <table border=\"2\" align=\"center\">\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Código</th>\r\n");
      out.write("                <th>Nombre</th>\r\n");
      out.write("                <th>Precio de Compra</th>\r\n");
      out.write("                <th>Precio de Venta</th>\r\n");
      out.write("                <th>Estado</th>\r\n");
      out.write("                <th>Descripción</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("            ");

            List<TblProductosusti> listado = (List<TblProductosusti>) request.getAttribute("listado");
            
            // Aplicamos una condición...
            if (listado != null) {
                // Aplicamos un bucle
                for (TblProductosusti lis : listado) {
            
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print( lis.getIdproductosusti() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( lis.getNombresusti() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( lis.getPreciocompsusti() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( lis.getPrecioventasusti() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( lis.getEstadosusti() );
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print( lis.getDescripsusti() );
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");

                }
            } else {
            
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"6\" align=\"center\">No hay productos registrados.</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            ");

            }
            
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
